<?
/**
 * @var string $redirectTo
 */
?>
<? $loginServices = view::getLoginServices($redirectTo, ' ile Bağlan'); ?>
<? if (count($loginServices)) { ?>
    <div class="socialLogin mb30">
        <p class="text-center"><strong>Sosyal medya hesabınızı kullanarak <?= icms::site_com("a") ?> kolayca giriş yapabilirsiniz.</strong></p>
        <div class="text-center">
            <?= implode('', $loginServices) ?>
        </div>
    </div>
<? } ?>
<div class="row mb30">
    <div class="col-md-4">
        <h2 class="block-title">Üye Girişi</h2>
        <div class="block">
            <p class="text-center">E-Posta ve Parolanızı kullanarak giriş yapabilirsiniz.</p>
            <form class="form-horizontal" id="login" role="form" action="/member/signin" method="post">
                <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 col-md-12 mb15">
                        <label for="LoginEmail">E-Posta Adresiniz:</label> <input type="email" name="email" onkeypress="return disableSpaceKey(event);" class="form-control"
                                id="LoginEmail">
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-12 mb15">
                        <label for="LoginPassword">Parolanız:</label> <input type="password" name="password" class="form-control" id="LoginPassword">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 text-left">
                        <button type="submit" class="btn btn-primary noiseBg">Giriş Yap</button>
                        <a class="textButton" href="/member/forgot_password">Parolamı Unuttum</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-8">
        <h2 class="block-title ">Üye Olmak İstiyorum</h2>
        <div class="block">
            <p class="text-center">Sadece aşağıdaki bilgilerini vererek sitemize üye olabilirsiniz.</p>
            <form novalidate="novalidate" class="form-horizontal" id="registerForm" role="form" action="/member/signup" method="post">
                <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                <div class="row">
                    <div class="col-xs-12 col-sm-6 mb15">
                        <label for="SignupName">Adınız:</label> <input type="text" name="firstname" class="form-control" id="SignupName">
                    </div>
                    <div class="col-xs-12 col-sm-6 mb15">
                        <label for="SignupSurname">Soyadınız:</label> <input type="text" name="surname" class="form-control" id="SignupSurname">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-6 mb15">
                        <label for="SignupEmail">E-Posta Adresi:</label> <input type="email" name="email" onkeypress="return disableSpaceKey(event);" class="form-control"
                                id="SignupEmail">
                    </div>
                    <div class="col-xs-12 col-sm-6 mb15">
                        <label for="SignupPassword">Parola:</label> <input type="password" name="passwd" class="form-control" id="SignupPassword">
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12 col-sm-12 text-left">
                        <div class="checkbox">
                            <label> <input type="checkbox" id="subscription" name="subscription" checked="checked">Kampanyalar ile ilgili e-posta mesajları almak istiyorum.</label>
                        </div>
                        <div class="mb15 mt15">
                            <button type="submit" class="btn btn-primary noiseBg">Hesabımı Oluştur</button>
                        </div>
                        <div class="">
                            Hesap oluşturarak <a class="b" href="javascript:" onclick="load_modal('/uyelik-sozlesmesi')" data-toggle="modal" data-target="#modalBox">üyelik
                                sözleşmesini</a> okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="modalBox" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalLabel">Kullanım Koşulları ve Gizlilik Sözleşmesi</h4>
            </div>
            <div class="modal-body clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function load_modal(page) {
        $.post(page, {ajax: 1}, function (data) {
            $('.modal-body').html(data)
        });
    }
    $(function () {
        $('input[name=email]').blur(function () {
            $(this).val(function (i, oldval) {
                return $.trim(oldval);
            });
        });
        $("#registerForm").validate($.extend(validationConfig, {
            rules: {
                email: {required: true, email: true},
                passwd: {required: true},
                firstname: {required: true, minlength: 2},
                surname: {required: true, minlength: 2}
            }
        }));
    });
</script>
