<?
/**
 * @var string $redirectTo
 * @var string $b64
 */
?>
<div class="modal fade" id="sign-up" tabindex="-1" role="dialog" aria-labelledby="signupLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="signupLabel">Sitemize Üye Olun</h4>
            </div>
            <div class="modal-body">
                <? $loginServices = view::getLoginServices($redirectTo); ?>
                <? if (count($loginServices)) { ?>
                    <div class="socialLogin mb30 text-center">
                        <p>Sosyal medya hesabınızı kullanarak <?= icms::site_com("a") ?> kolayca üye olabilirsiniz.</p>
                        <div>
                            <?= implode('', $loginServices) ?>
                        </div>
                    </div>
                <? } ?>
                <div class="text-center">
                    <p class="text-center">Sitemize üye olmak için aşağıdaki formu doldurmanız yeterlidir.</p>
                    <form novalidate="novalidate" class="form-horizontal" id="registerForm" role="form" action="/ajax/signup" method="post">
                        <input type="hidden" name="redirectTo" value="<?= $redirectTo ?>">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 mb15">
                                <label for="SignupName">Adınız:</label> <input type="text" name="firstname" class="form-control" id="SignupName">
                            </div>
                            <div class="col-xs-12 col-sm-6 mb15">
                                <label for="SignupSurname">Soyadınız:</label> <input type="text" name="surname" class="form-control" id="SignupSurname">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 mb15">
                                <label for="SignupEmail">E-Posta Adresi:</label> <input type="email" name="email" onkeypress="return disableSpaceKey(event);" class="form-control"
                                        id="SignupEmail">
                            </div>
                            <div class="col-xs-12 col-sm-6 mb15">
                                <label for="SignupPassword">Parola:</label> <input type="password" name="passwd" class="form-control" id="SignupPassword">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 text-left">
                                <div class="checkbox">
                                    <label> <input type="checkbox" id="subscription" name="subscription" checked="checked">Kampanyalar ile ilgili e-posta mesajları almak istiyorum.</label>
                                </div>
                                <div class="mb15 mt15">
                                    <button type="submit" class="btn btn-primary submitButton">Hesabımı Oluştur</button>
                                </div>
                                <div class="">
                                    Hesap oluşturarak <a class="b" href="javascript:" onclick="load_modal('/uyelik-sozlesmesi')" data-toggle="modal" data-target="#modalBox">üyelik
                                        sözleşmesini</a> okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
