<?php
/**
 * @var array $parentCategories
 * @var array $subCategories
 * @var array $filterGroups
 */
?>
<!-- secimler -->
<? if (count($subCategories)) { ?>
    <div class="filter-content">
        <h2 class="title-block">KATEGORİ</h2>
        <div class="block mb15">
            <ul class="nav">
                <? foreach ($subCategories as $category) { ?>
                    <li><a href="<?= $category['link'] ?>"><?= $category['title'] ?></a></li>
                <? } ?>
            </ul><!-- #nav# -->
        </div><!-- #block# -->
    </div><!-- #filter-content# -->
<? } ?>
<? if (count($filterGroups)) { ?>
    <? foreach ($filterGroups as $filterGroup) { ?>
        <div class="filter-content">
            <h2 class="title-block"><?= $filterGroup['title'] ?></h2>
            <div class="block mb15">
                <ul class="nav scrollbar">
                    <? foreach ($filterGroup['items'] as $item) { ?>
                        <li><a href="<?= $item['link'] ?>"><?= $item['title'] ?> (<?= $item['resultCount'] ?>)</a></li>
                    <? } ?>
                </ul><!-- #nav# -->
            </div><!-- #block# -->
        </div>
    <? } ?>
<? } ?>
