<?
/**
 * @var int             $id
 * @var string          $title
 * @var \product_item[] $products
 */
?>
<div id="<?= $id ?>" class="filter-products-wrapper mb30">
    <div class="filter-products-title"><?= $title ?></div>
    <div class="owl-carousel owl-theme owl-filter-product">
        <? foreach ($products as $key => $product) { ?>
            <div class="item">
                <div class="product-list">
                    <div class="product-wrapper">
                        <?= $product->generate() ?>
                    </div>
                </div>
            </div>
        <? } ?>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#<?=$id?> .owl-carousel').owlCarousel({
            items: 6,
            lazyLoad: true,
            loop: true,
            margin: 0,
            nav: true,
            dots: false,
            autoplay: true,
            autoplayTimeout: 4000,
            autoplayHoverPause: true,
            responsiveClass: true,
            responsiveBaseElement: '#<?=$id?>',
            responsive: {
                0: {
                    items: 1,
                    nav: false
                },
                320: {
                    items: 2
                },
                550: {
                    items: 3
                },
                768: {
                    items: 4
                },
                992: {
                    items: 6
                }
            },
            slideSpeed: 300,
            paginationSpeed: 400,
            navText: ['<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>', '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>']
        });
    });
</script>
