<!DOCTYPE html>
<html lang="tr">
<?= view::load("head") ?>
<body lang="tr">
<?= view::facebook_sdk() ?>
<div id="bodyWrapper">
    <?= view::load("header") ?>
    <?= view::showMessages('class="messageBox container" style="display:none"') ?>
    <div class="container">
        <? if (view::has_blocks()) { ?>
            <div class="row mb30">
                <article class="col-xs-12 col-sm-8 col-md-9 pull-right">
                    <section>
                        <? view::show_contents() ?>
                    </section>
                </article>
                <? view::show_blocks("col-xs-12 col-sm-4 col-md-3 pull-left") ?>
            </div>
        <? } else { ?>
            <? view::show_contents() ?>
        <? } ?>
    </div>
    <!-- container sonu -->
    <?= view::load("footer") ?>
</div>
</body>
</html>
